service: puffin
  

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  environment:
    DB_HOST: ${env:DB_HOST, ssm:/myapp/db-host}
    DB_USER: ${env:DB_USER, ssm:/myapp/db-user}
    DB_PASSWORD: ${env:DB_PASSWORD, ssm:/myapp/db-password}
    DB_NAME: ${env:DB_NAME, ssm:/myapp/db-name}
    APIFY_TOKEN: ${env:APIFY_TOKEN, ssm:/myapp/apify-token}
  vpc:
    securityGroupIds:
      - sg-0123456789abcdef  # ✅ RDS에 접근 가능한 SG ID
    subnetIds:
      - subnet-abc12345
      - subnet-def67890

functions:
  call-profile-actor:
    handler: dist/functions/callProfileActor.main
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ScrapingQueue
              - Arn
          batchSize: 10

plugins:
  - serverless-dotenv-plugin
